# Generated by Django 3.2.3 on 2021-05-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinehub_backend', '0003_alter_movie_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='running_movies',
            name='running_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
