# Generated by Django 3.2.3 on 2021-05-27 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinehub_backend', '0007_running_movies_unique_movie_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='running_movies',
            old_name='imdb',
            new_name='movie',
        ),
    ]
